### ISSUE TITLE
Using keyboard shortcut for "Go to definition" (F12) doesn't work like ctrl + click

### ISSUE THREAD

**Issue by Arcensoth** [SPGoding/datapack-language-server#196]
When I use ctrl + click to go to the definition of a function, it works great:

![image](https://user-images.githubusercontent.com/1885643/70177305-1d4b1c80-16a8-11ea-8048-95f848e55eea.png)

But if I use the keyboard shortcut (F12), it only reads a single word around the cursor instead of the whole namespaced ID:

![image](https://user-images.githubusercontent.com/1885643/70177375-423f8f80-16a8-11ea-9fb3-bf85e96b0fbe.png)

Is there another shortcut for this, or am I using the wrong one?

**Comment by SPGoding** [comment]
There are two functions involved in this issue: `Go To Definition` and `Follow Document Link`.

Namespaced IDs are treated as document links, which is the same thing VSCode uses to represent web URLs in a document. Function files currently are not considered a definition of a namespaced ID, so it's impossible to use the go to definition shortcut to navigate to the specific function file. You can use F12 to go to the definition of a bossbar, an entity name, a scoreboard objective, a scoreboard tag or a team, however. 

I've found a question you may be interested in: [What is the shortcut for CTRL + CLICK in Visual Code?
](https://stackoverflow.com/questions/49861033/what-is-the-shortcut-for-ctrl-click-in-visual-code). Unfortunately due to my test you can't assign F12 to both `Go To Definition` and `Follow Document Link` :/

Should I start treating function files as definitions of IDs, everything would be great: you could use both the two functions to navigate to a function file. But I'm just too lazy to do that 🏃

**Comment by Arcensoth** [comment]
Ah! Thanks for the clarification. I added my own shortcut for `Follow Document Link` and it works just fine.

Here's the configuration in `keybindings.json` for posterity:

```
  {
    "key": "ctrl+f12",
    "command": "editor.action.openLink",
    "when": "editorTextFocus"
  }
```

**Comment by SPGoding** [comment]
> Should I start treating function files as definitions of IDs, everything would be great: you could use both the two functions to navigate to a function file.

It will come true in 3.0.0 as another user requested this feature at #605.
