### ISSUE TITLE
When setting "Health" to item entity in data merge, float type is required for value (short type is correct)

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#225]
Health for normal entities (float type)
Health (short type) for item entity

**Comment by SPGoding** [comment]
![image](https://user-images.githubusercontent.com/15277496/71446760-74af3c00-26ec-11ea-9da6-fca4360d5a4a.png)

If the entity selector involved in the command doesn't explicity set the type to `minecraft:item`, the extension will use the schema of mob to check NBTs. I don't think this is easy to fix :thinking:.

Maybe just set the default schema to entity's instead of mob's
