### ISSUE TITLE
New #define arguments

### ISSUE THREAD

**Issue by mathaym25** [SPGoding/datapack-language-server#382]
It is very useful to be able to use `#define` for fakeplayers.
However, the only current way to do this is to put them in `#define entity`. But this implies that they are visible in the fields reserved for entities.
It could be useful to have a `#define fakeplayer <name> <descritpion>` which is self-completing only in the fields linked to the scores (`execute if score <fakeplayer or entity> <score>` for example)

It can also be useful to have a #define nbt to auto complete our custom structures in the `tag:{}` of items or storages. (`#define nbt Foo:["this is","a test"] And this is a description` for example)

But also, in certain cases, a `#define path` to auto complete with our structures the path arguments (for `data modify` for example).

**Comment by SPGoding** [comment]
I'd like to use `#define score_holder` (`score_holder` is the name of the parser that Minecraft uses [internally](https://minecraft.gamepedia.com/Argument_types#minecraft:score_holder)) instead of `#define fakeplayer`.

NBT-related stuff still has to be considered since I have a plan for doc comment at #1. It probably won't come in the next version, sorry ;(
