### ISSUE TITLE
Use textEdit instead of insertText; bad autocompletion for special characters

### ISSUE THREAD

**Issue by mathaym25** [SPGoding/datapack-language-server#435]
![Report DHP](https://user-images.githubusercontent.com/35702771/80425233-8e070580-88e3-11ea-837b-7c832b2a2441.gif)

**Comment by SPGoding** [comment]
This issue has become critical as it blocks the process of merging JSON support logic in (#342).

VS Code requires all `CompletionItem`s for JSON files contain a [`range` property](https://github.com/microsoft/vscode/blob/4c99db1a05687a67c1d214361946b18e5f65e0cf/src/vs/vscode.d.ts#L3856), whose type is `Range | { inserting: Range, replacing: Range }`.

The Language Server Protocol still hasn't any support for it, so we need to use the existing `textEdit` property instead. However it's desirable to support the new `range` logic since `textEdit` has been deprecated in VS Code, so instead of building LSP's `CompletionItem`s directly, using an inner type would be preferable: 
```typescript
interface ParserSuggestion extends CompletionItem {
    /**
     * The start offset of the CompletionItem.
     */
    start: number,
    /**
     * The end offset of the CompletionItem in replacing cases.
     */
    replaceEnd: number,
    /**
     * The end offset of the CompletionItem in inserting cases.
     */
    insertEnd: number
}
```

This refactor requires a huge rewrite in almost every parser and their corresponding tests, hope I can survive it :D
